// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Data;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApplication1.Models.Barber", b =>
                {
                    b.Property<int>("BarberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BarberId"));

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("BarberId");

                    b.ToTable("Barber");

                    b.HasData(
                        new
                        {
                            BarberId = 1,
                            BirthDate = new DateOnly(1990, 5, 12),
                            Name = "Adam",
                            Surname = "Kowalski"
                        },
                        new
                        {
                            BarberId = 2,
                            BirthDate = new DateOnly(1996, 7, 23),
                            Name = "Jakub",
                            Surname = "Nowak"
                        },
                        new
                        {
                            BarberId = 3,
                            BirthDate = new DateOnly(2001, 1, 6),
                            Name = "Michal",
                            Surname = "Wojcik"
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClientId"));

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ClientId");

                    b.ToTable("Client");

                    b.HasData(
                        new
                        {
                            ClientId = 1,
                            BirthDate = new DateOnly(1991, 4, 18),
                            Name = "Mateusz",
                            Surname = "Kowalczyk"
                        },
                        new
                        {
                            ClientId = 2,
                            BirthDate = new DateOnly(1988, 9, 7),
                            Name = "Agnieszka",
                            Surname = "Nowak"
                        },
                        new
                        {
                            ClientId = 3,
                            BirthDate = new DateOnly(1994, 12, 22),
                            Name = "Krzysztof",
                            Surname = "Zielinski"
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.Visit", b =>
                {
                    b.Property<int>("VisitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VisitId"));

                    b.Property<int>("BarberId")
                        .HasColumnType("int");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("End")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime2");

                    b.HasKey("VisitId");

                    b.HasIndex("BarberId");

                    b.HasIndex("ClientId");

                    b.ToTable("Visit");

                    b.HasData(
                        new
                        {
                            VisitId = 1,
                            BarberId = 1,
                            ClientId = 1,
                            Comment = "Strzyrzenie",
                            End = new DateTime(2025, 1, 5, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            Price = 110m,
                            Start = new DateTime(2025, 1, 5, 15, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            VisitId = 2,
                            BarberId = 1,
                            ClientId = 2,
                            Comment = "Golenie",
                            End = new DateTime(2025, 2, 18, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 75m,
                            Start = new DateTime(2025, 2, 18, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            VisitId = 3,
                            BarberId = 3,
                            ClientId = 3,
                            Comment = "Strzyrzenie + golenie",
                            End = new DateTime(2025, 3, 1, 18, 30, 0, 0, DateTimeKind.Unspecified),
                            Price = 150m,
                            Start = new DateTime(2025, 3, 1, 17, 10, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.Visit", b =>
                {
                    b.HasOne("WebApplication1.Models.Barber", "Barber")
                        .WithMany("Visits")
                        .HasForeignKey("BarberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication1.Models.Client", "Client")
                        .WithMany("Visits")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Barber");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("WebApplication1.Models.Barber", b =>
                {
                    b.Navigation("Visits");
                });

            modelBuilder.Entity("WebApplication1.Models.Client", b =>
                {
                    b.Navigation("Visits");
                });
#pragma warning restore 612, 618
        }
    }
}
